import Head from "next/head";
import DottedLine from "../components/Item/DottedLine";
import styles from "../styles/home.module.css";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();

  const moveToCtrlf = () => {
    router.push("/works/ctrlf");
  };

  const moveToTras = () => {
    router.push("/works/tras");
  };
  return (
    <>
      <Head>
        <title>JSH-PORTFOLIO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <img className={styles.road} src="/images/home/road.png" />

        <div className={styles.introduction}>
          <div className={styles.picture}></div>
          <div>도전을 즐기는 개발자 정승화 입니다. </div>
        </div>
        <div className={styles.wrap__tras}>
          <img
            className={styles.tras}
            src="/images/home/work_TRAS.png"
            onClick={moveToTras}
          />
        </div>
        <div className={styles.wrap__ctrlf}>
          <img
            className={styles.ctrlf}
            src="/images/home/work_ctrlf.png"
            onClick={moveToCtrlf}
          />
        </div>
      </main>
    </>
  );
}
