import Head from "next/head";
import Image from "next/image";
import Footer from "../components/Layout/Footer";
import Nav from "../components/Layout/Navbar";
import styles from "../styles/Layout/home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>JSH-PORTFOLIO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main>
        <div className={styles.main}>여기는 본문입니당</div>
      </main>
      <Footer />
    </>
  );
}
